Move all OAuth config to conf.d directory
pivotal-cf/cf-rabbitmq-release pull request #435
Opened 2021-02-22 17:12 UTC by coro

As of https://github.com/rabbitmq/rabbitmq-server/pull/2833, it is
possible to fully configure OAuth in the release through the
Cuttlefish-style conf.d config files. This PR moves any conflicting
advanced.config OAuth configuration to these files.

A pre-requisite of this PR is
https://github.com/pivotal-cf/cf-rabbitmq-release/pull/429 and the
release of RabbitMQ 3.8.13.

2021-03-08 11:09 UTC, ansd requested changes

2021-03-08 11:09 UTC, ansd commented on jobs/rabbitmq-server/templates/config-files/advanced.config.erb
> -].
https://github.com/rabbitmq/rabbitmq-server/pull/2833#issue-577666919:
> Symmetric key configuration still requires the old syntax and therefore can be configured using advanced config file.

With the changes in the PR, job property `rabbitmq-server.oauth.signing_key` can't be a symmetric key anymore.
That's okay given that support for symmetric keys will be removed in a future version (see https://rabbitmq.slack.com/archives/C1EDN83PA/p1614346342187000?thread_ts=1614322730.168400&cid=C1EDN83PA).

However, let's adapt the description in https://github.com/pivotal-cf/cf-rabbitmq-release/blob/76a865f3b87aba68d4648dc5ce0c94e9ffaf9b10/jobs/rabbitmq-server/spec#L116 by removing the part "or the symmetric signing key".

2021-03-12 09:00 UTC, ansd approved these changes

2021-03-12 10:17 UTC, ablease reviewed
LGTM

2021-03-12 12:22 UTC, merged